spring.application.name=hse

spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/hse
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=hse_schema


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.jackson.serialization.write-dates-as-timestamps=false

spring.config.import=optional:file:.env[.properties]
jwt.secret=${JWT_SECRET}
frontend.url=${FRONTEND_URL:http://localhost:5173}

#server.address=0.0.0.0

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
hse.mail.from=${MAIL_FROM:andersonmahosi@gmail.com}
hse.mail.from.name=${MAIL_FROM_NAME:Département HSE Stellarix}
hse.mail.phone=${MAIL_PHONE:+261 00 00 000 00}


