ALTER TABLE hse_schema.hse
    ADD COLUMN IF NOT EXISTS failed_attempts      INTEGER   NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS locked_until         TIMESTAMP,
    ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN   NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS totp_secret          VARCHAR(64),
    ADD COLUMN IF NOT EXISTS totp_enabled         BOOLEAN   NOT NULL DEFAULT FALSE;
